target 'TFLayoutConstraintsFactory', :exclusive => true do
  pod "TFLayoutConstraintsFactory", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TFLayoutConstraintsFactory", :path => "../"
end
